openapi: 3.0.0
info:
  title: Exemplo de API OWASP
  version: "1.0.0"
servers:
  - url: http://api.insegura.com
paths:
  /users:
    get:
      summary: Users List
      security: []
      parameters:
        - name: filter
          in: query
          description: Filter without type
      responses:
        "200":
          description: OK
    post:
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created
  /create:
    get:
      summary: Insecure creation via GET
      operationId: createUser
      responses:
        "200":
          description: OK
  /debug:
    trace:
      summary: Insecure TRACE method
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: []
