version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  swagger_guard:
    build: .
    image: app/swagger_guard:latest
    container_name: swagger_guard
    environment:
      - LOG_LEVEL=info
      - OUTPUT_FORMAT=cli
      - OUTPUT_FILE=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: ["parse", "--file", "api-spec.yaml", "--output", "cli"]