name: Swagger Guard Scan
on:
  push:
    paths:
      - "api-spec.yaml"
  pull_request:
    paths:
      - "api-spec.yaml"

jobs:
  scan:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: [6379:6379]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go mod tidy
      - name: Run Swagger Guard
        run: go run main.go parse --file api-spec.yaml --output cli
